# Copyright (c) 2026 Marco Fortina
# SPDX-License-Identifier: AGPL-3.0-only
#
# This file is part of Custodia.
# Custodia is distributed under the GNU Affero General Public License v3.0.
# See the accompanying LICENSE file for details.

apiVersion: v1
kind: Service
metadata:
  name: cockroachdb-public
  namespace: custodia-db
  labels:
    app.kubernetes.io/name: cockroachdb
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: cockroachdb
  ports:
    - name: sql
      port: 26257
      targetPort: sql
    - name: http
      port: 8080
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: cockroachdb
  namespace: custodia-db
  labels:
    app.kubernetes.io/name: cockroachdb
    app.kubernetes.io/component: database
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: cockroachdb
  ports:
    - name: sql
      port: 26257
      targetPort: sql
    - name: gossip
      port: 26258
      targetPort: gossip
