apiVersion: v1
kind: Secret
metadata:
  name: custodia-database
  namespace: custodia
  labels:
    app.kubernetes.io/name: custodia
    app.kubernetes.io/component: database-config
type: Opaque
stringData:
  database-url: postgresql://custodia@cockroachdb-public.custodia-db.svc.cluster.local:26257/custodia?sslmode=disable
