# Copyright (c) 2026 Marco Fortina
# SPDX-License-Identifier: AGPL-3.0-only
#
# This file is part of Custodia.
# Custodia is distributed under the GNU Affero General Public License v3.0.
# See the accompanying LICENSE file for details.

apiVersion: v1
kind: Namespace
metadata:
  name: custodia-db
  labels:
    app.kubernetes.io/name: custodia-cockroachdb
    app.kubernetes.io/component: database
