# Copyright (c) 2026 Marco Fortina
# SPDX-License-Identifier: AGPL-3.0-only
#
# This file is part of Custodia.
# Custodia is distributed under the GNU Affero General Public License v3.0.
# See the accompanying LICENSE file for details.

{{- if .Values.signer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "custodia.signerFullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "custodia.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: signer
{{- with .Values.signer.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: ClusterIP
  ports:
    - name: signer
      port: {{ .Values.signer.service.port }}
      targetPort: signer
  selector:
    app.kubernetes.io/name: {{ include "custodia.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: signer
{{- end }}
