// Copyright (c) 2026 Marco Fortina
// SPDX-License-Identifier: AGPL-3.0-only
//
// This file is part of Custodia.
// Custodia is distributed under the GNU Affero General Public License v3.0.
// See the accompanying LICENSE file for details.

package client

import (
	"fmt"
	"net/http"
	"net/url"
	"strings"
)

func (c *Client) CurrentClientInfo() (ClientInfo, error) {
	var response ClientInfo
	return response, c.doJSON(http.MethodGet, "/v1/me", nil, &response)
}

func (c *Client) ListClientInfos(filters ClientListFilters) ([]ClientInfo, error) {
	if err := validateOptionalLimit(filters.Limit); err != nil {
		return nil, err
	}
	query := url.Values{}
	if filters.Limit > 0 {
		query.Set("limit", fmt.Sprintf("%d", filters.Limit))
	}
	if filters.Active != nil {
		query.Set("active", fmt.Sprintf("%t", *filters.Active))
	}
	path := "/v1/clients"
	if encoded := query.Encode(); encoded != "" {
		path += "?" + encoded
	}
	var response struct {
		Clients []ClientInfo `json:"clients"`
	}
	err := c.doJSON(http.MethodGet, path, nil, &response)
	return response.Clients, err
}

func (c *Client) GetClientInfo(clientID string) (ClientInfo, error) {
	var response ClientInfo
	return response, c.doJSON(http.MethodGet, "/v1/clients/"+pathEscape(clientID), nil, &response)
}

func (c *Client) CreateClientInfo(req CreateClientPayload) error {
	return c.doJSON(http.MethodPost, "/v1/clients", req, nil)
}

func (c *Client) RevokeClientInfo(req RevokeClientPayload) error {
	return c.doJSON(http.MethodPost, "/v1/clients/revoke", req, nil)
}

// CreateSecretPayload is transport-only: callers must provide ciphertext, metadata and envelopes already produced client-side.
func (c *Client) CreateSecretPayload(req CreateSecretPayload) (SecretVersionRef, error) {
	var ref SecretVersionRef
	return ref, c.doJSON(http.MethodPost, "/v1/secrets", req, &ref)
}

func (c *Client) GetSecretPayload(secretID string) (SecretReadResponse, error) {
	var response SecretReadResponse
	return response, c.doJSON(http.MethodGet, "/v1/secrets/"+pathEscape(secretID), nil, &response)
}

func (c *Client) GetSecretPayloadByKey(namespace, key string) (SecretReadResponse, error) {
	path, err := secretByKeyPath("/v1/secrets/by-key", namespace, key, false)
	if err != nil {
		return SecretReadResponse{}, err
	}
	var response SecretReadResponse
	return response, c.doJSON(http.MethodGet, path, nil, &response)
}

func (c *Client) ListSecretMetadataPublic(limit int) ([]SecretMetadata, error) {
	return c.ListSecretMetadata(limit)
}

func (c *Client) ListSecretMetadata(limit int) ([]SecretMetadata, error) {
	if err := validateOptionalLimit(limit); err != nil {
		return nil, err
	}
	path := "/v1/secrets"
	if limit > 0 {
		query := url.Values{}
		query.Set("limit", fmt.Sprintf("%d", limit))
		path += "?" + query.Encode()
	}
	var response struct {
		Secrets []SecretMetadata `json:"secrets"`
	}
	err := c.doJSON(http.MethodGet, path, nil, &response)
	return response.Secrets, err
}

func (c *Client) ListSecretVersionMetadata(secretID string, limit int) ([]SecretVersionMetadata, error) {
	if err := validateOptionalLimit(limit); err != nil {
		return nil, err
	}
	path := "/v1/secrets/" + pathEscape(secretID) + "/versions"
	if limit > 0 {
		query := url.Values{}
		query.Set("limit", fmt.Sprintf("%d", limit))
		path += "?" + query.Encode()
	}
	var response struct {
		Versions []SecretVersionMetadata `json:"versions"`
	}
	err := c.doJSON(http.MethodGet, path, nil, &response)
	return response.Versions, err
}

func (c *Client) ListSecretVersionMetadataByKey(namespace, key string, limit int) ([]SecretVersionMetadata, error) {
	path, err := secretByKeyPathWithLimit("/v1/secrets/by-key/versions", namespace, key, false, limit)
	if err != nil {
		return nil, err
	}
	var response struct {
		Versions []SecretVersionMetadata `json:"versions"`
	}
	err = c.doJSON(http.MethodGet, path, nil, &response)
	return response.Versions, err
}

func (c *Client) ListSecretAccessMetadata(secretID string, limit int) ([]SecretAccessMetadata, error) {
	if err := validateOptionalLimit(limit); err != nil {
		return nil, err
	}
	path := "/v1/secrets/" + pathEscape(secretID) + "/access"
	if limit > 0 {
		query := url.Values{}
		query.Set("limit", fmt.Sprintf("%d", limit))
		path += "?" + query.Encode()
	}
	var response struct {
		Access []SecretAccessMetadata `json:"access"`
	}
	err := c.doJSON(http.MethodGet, path, nil, &response)
	return response.Access, err
}

func (c *Client) ListSecretAccessMetadataByKey(namespace, key string, limit int) ([]SecretAccessMetadata, error) {
	path, err := secretByKeyPathWithLimit("/v1/secrets/by-key/access", namespace, key, false, limit)
	if err != nil {
		return nil, err
	}
	var response struct {
		Access []SecretAccessMetadata `json:"access"`
	}
	err = c.doJSON(http.MethodGet, path, nil, &response)
	return response.Access, err
}

// ShareSecretPayload uploads an opaque recipient envelope generated by an authorized client; the server never derives it.
func (c *Client) ShareSecretPayload(secretID string, req ShareSecretPayload) error {
	return c.doJSON(http.MethodPost, "/v1/secrets/"+pathEscape(secretID)+"/share", req, nil)
}

func (c *Client) ShareSecretPayloadByKey(namespace, key string, req ShareSecretPayload) error {
	path, err := secretByKeyPath("/v1/secrets/by-key/share", namespace, key, false)
	if err != nil {
		return err
	}
	return c.doJSON(http.MethodPost, path, req, nil)
}

func (c *Client) RevokeAccessByKey(namespace, key, targetClientID string) error {
	path, err := secretByKeyPath("/v1/secrets/by-key/access/"+pathEscape(targetClientID), namespace, key, false)
	if err != nil {
		return err
	}
	return c.doJSON(http.MethodDelete, path, nil, nil)
}

func (c *Client) CreateAccessGrantByKey(namespace, key string, req AccessGrantPayload) (AccessGrantRef, error) {
	path, err := secretByKeyPath("/v1/secrets/by-key/access-requests", namespace, key, false)
	if err != nil {
		return AccessGrantRef{}, err
	}
	var ref AccessGrantRef
	return ref, c.doJSON(http.MethodPost, path, req, &ref)
}

func (c *Client) ActivateAccessGrantPayloadByKey(namespace, key, targetClientID string, req ActivateAccessPayload) error {
	path, err := secretByKeyPath("/v1/secrets/by-key/access/"+pathEscape(targetClientID)+"/activate", namespace, key, false)
	if err != nil {
		return err
	}
	return c.doJSON(http.MethodPost, path, req, nil)
}

func (c *Client) CreateSecretVersionPayload(secretID string, req CreateSecretVersionPayload) (SecretVersionRef, error) {
	var ref SecretVersionRef
	return ref, c.doJSON(http.MethodPost, "/v1/secrets/"+pathEscape(secretID)+"/versions", req, &ref)
}

func (c *Client) CreateSecretVersionPayloadByKey(namespace, key string, req CreateSecretVersionPayload) (SecretVersionRef, error) {
	path, err := secretByKeyPath("/v1/secrets/by-key/versions", namespace, key, false)
	if err != nil {
		return SecretVersionRef{}, err
	}
	var ref SecretVersionRef
	return ref, c.doJSON(http.MethodPost, path, req, &ref)
}

func secretByKeyPath(basePath, namespace, key string, cascade bool) (string, error) {
	return secretByKeyPathWithLimit(basePath, namespace, key, cascade, 0)
}

func secretByKeyPathWithLimit(basePath, namespace, key string, cascade bool, limit int) (string, error) {
	if err := validateOptionalLimit(limit); err != nil {
		return "", err
	}
	namespace = strings.TrimSpace(namespace)
	if namespace == "" {
		namespace = "default"
	}
	key = strings.TrimSpace(key)
	if key == "" {
		return "", fmt.Errorf("secret key is required")
	}
	query := url.Values{}
	query.Set("namespace", namespace)
	query.Set("key", key)
	if cascade {
		query.Set("cascade", "true")
	}
	if limit > 0 {
		query.Set("limit", fmt.Sprintf("%d", limit))
	}
	return basePath + "?" + query.Encode(), nil
}

func (c *Client) ListAccessGrantMetadata(filters AccessGrantRequestFilters) ([]AccessGrantMetadata, error) {
	if err := validateAccessGrantRequestFilters(filters); err != nil {
		return nil, err
	}
	query := url.Values{}
	if filters.Limit > 0 {
		query.Set("limit", fmt.Sprintf("%d", filters.Limit))
	}
	addQueryFilter(query, "secret_id", filters.SecretID)
	addQueryFilter(query, "status", filters.Status)
	addQueryFilter(query, "client_id", filters.ClientID)
	addQueryFilter(query, "requested_by_client_id", filters.RequestedByClientID)
	path := "/v1/access-requests"
	if encoded := query.Encode(); encoded != "" {
		path += "?" + encoded
	}
	var response struct {
		AccessRequests []AccessGrantMetadata `json:"access_requests"`
	}
	err := c.doJSON(http.MethodGet, path, nil, &response)
	return response.AccessRequests, err
}

func (c *Client) StatusInfo() (OperationalStatus, error) {
	var response OperationalStatus
	return response, c.doJSON(http.MethodGet, "/v1/status", nil, &response)
}

func (c *Client) VersionInfo() (BuildInfo, error) {
	var response BuildInfo
	return response, c.doJSON(http.MethodGet, "/v1/version", nil, &response)
}

func (c *Client) DiagnosticsInfo() (RuntimeDiagnostics, error) {
	var response RuntimeDiagnostics
	return response, c.doJSON(http.MethodGet, "/v1/diagnostics", nil, &response)
}

func (c *Client) RevocationStatusInfo() (RevocationStatus, error) {
	var response RevocationStatus
	return response, c.doJSON(http.MethodGet, "/v1/revocation/status", nil, &response)
}

func (c *Client) RevocationSerialStatusInfo(serialHex string) (RevocationSerialStatus, error) {
	var response RevocationSerialStatus
	path := "/v1/revocation/serial?serial_hex=" + url.QueryEscape(strings.TrimSpace(serialHex))
	return response, c.doJSON(http.MethodGet, path, nil, &response)
}

func (c *Client) ListAuditEventMetadata(filters AuditEventFilters) ([]AuditEvent, error) {
	if err := validateAuditEventFilters(filters); err != nil {
		return nil, err
	}
	query := url.Values{}
	if filters.Limit > 0 {
		query.Set("limit", fmt.Sprintf("%d", filters.Limit))
	}
	addQueryFilter(query, "outcome", filters.Outcome)
	addQueryFilter(query, "action", filters.Action)
	addQueryFilter(query, "actor_client_id", filters.ActorClientID)
	addQueryFilter(query, "resource_type", filters.ResourceType)
	addQueryFilter(query, "resource_id", filters.ResourceID)
	path := "/v1/audit-events"
	if encoded := query.Encode(); encoded != "" {
		path += "?" + encoded
	}
	var response struct {
		AuditEvents []AuditEvent `json:"audit_events"`
	}
	err := c.doJSON(http.MethodGet, path, nil, &response)
	return response.AuditEvents, err
}

func (c *Client) ExportAuditEventArtifact(filters AuditEventFilters) (AuditExportArtifact, error) {
	return c.ExportAuditEventsWithMetadata(filters)
}
